# Render 배포 설정 파일
services:
  # Ollama 서버
  - type: web
    name: ollama-server
    env: docker
    dockerfilePath: ./Dockerfile.ollama
    plan: free
    region: oregon
    healthCheckPath: /api/tags
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0
      - key: OLLAMA_ORIGINS
        value: "*"
    # 프리플랜 최적화 설정
    scaling:
      minInstances: 0
      maxInstances: 1
    # 자동 스핀다운 방지 (가능한 경우)
    autoDeploy: true

  # Next.js 앱
  - type: web
    name: admate-chatbot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OLLAMA_BASE_URL
        value: https://ollama-server-4dx3.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://renjseslaqgfoxslxlyu.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlbmpzZXNsYXFnZm94c2x4bHl1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Njc4ODQ0MCwiZXhwIjoyMDcyMzY0NDQwfQ.ZP-psPigdwWdWQxUbiCeJo9C2Gb5j9fALtQOcIrmaWI
      - key: OLLAMA_MODEL
        value: qwen2.5:1.5b
      - key: OLLAMA_EMBEDDING_MODEL
        value: nomic-embed-text
    # 프리플랜 최적화 설정
    scaling:
      minInstances: 0
      maxInstances: 1
    autoDeploy: true