[start]
cmd = "cd railway-backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/railway-backend"

[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmd = "cd railway-backend && pip install -r requirements.txt"
